site_name: phisherman.py
site_url: https://phisherman.readthedocs.io

repo_url: https://github.com/QristaLabs/phisherman.py/
repo_name: QristaLabs/phisherman.py

theme:
  palette: 
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon: 
    repo: fontawesome/brands/github
  name: "material"

nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
        - Application: workflow-reference.md

plugins:
  - search
  - mkdocstrings